# apiVersion: meta.pkg.crossplane.io/v1
# kind: Configuration
# metadata:
#   name: module
# spec:
#   crossplane:
#     version: ">=v1.6"
#   dependsOn:
#   - provider: crossplane/provider-aws
#     version: v0.22.0